/** Local Roman-Hinglish copy for the Recharge tab + RechargeSheet (extends `t.wallet`). */
export const copy = {
  overline: "Aapke 💎",
  streakChip: "🔥 {n} din",
  streakStart: "🔥 Aaj streak shuru karo",
  freeChip: "Aaj {left}/{total} free",
  offerTitle: "₹{price} mein {credits} 💎",
  offerSub: "Sirf ek baar · naye users ke liye",
  offerCta: "₹{price} mein lo",
  normally: "₹{n}",
  perMessage: "₹{x}/message",
  save: "SAVE {n}%",
  packsTitle: "Packs chuno",
  neverExpire: "💎 kabhi expire nahi honge",
  howTitle: "💎 kaise kaam karte hain",
  how: [
    { icon: "chatbubble-ellipses", text: "1 💎 = 1 message" },
    { icon: "image", text: "Photo 3 💎, sirf jab tum dekho" },
    { icon: "gift", text: "Roz 5 messages free" },
    { icon: "flame", text: "Streak: din 3 +5, din 7 +15 💎" },
  ],
  trustTitle: "100% safe aur private",
  bankName: "Bank statement mein naam: Playmate Digital",
  upi: ["UPI", "GPay", "PhonePe", "Paytm"],
  paymentSoon: "Payment jaldi aa raha hai 🙏 Thoda intezaar karo",
  celebrateSub: "Ab baat jaari rakho 💬",
  sheet: {
    out_of_credits: { emoji: "😮", title: "Arre, 💎 khatam!", sub: "Baat jaari rakhne ke liye recharge karo" },
    photo: { emoji: "📸", title: "Photo dekhne ke liye 💎 chahiye", sub: "Ek chhota recharge, aur photo tumhari" },
    low_balance: { emoji: "⏳", title: "Sirf thode 💎 bache hain", sub: "Baat beech mein na ruke 💬" },
  },
  sheetBalance: "Balance: {n} 💎",
  sheetMore: "Saare packs dekho",
} as const;
